# -*- coding: utf-8 -*-
"""Week6_A105260034_魏嘉亨.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sdO6v3C56TwEEXrw-cnnrDDwqBHMafyj
"""

#1.求三數總和與平均
第一次期中考=int(input('請輸入第一次期中考成績'))
第二次期中考=int(input('請輸入第二次期中考成績'))
期末考=int(input('請輸入期末考成績'))
總分=第一次期中考+第二次期中考+期末考
平均=總分/3
print('總分為',總分)
print('平均',平均)

#2.英制轉公制
尺=int(input('請輸入幾尺'))
吋=int(input('請輸入幾吋'))
公分=(尺*12+吋)*2.54
print('轉換成',公分) #公分

#3.分組報告
座號=int(input('請輸入座號?'))
組別=int(座號/4)
print('組別為',組別)

#4.賣場買飲料
罐數=int(input('請輸入購買罐數?'))
打=int(罐數/12)
花費=(打*200)+(罐數-打*12)*20
print('需花費',花費)

