# -*- coding: utf-8 -*-
"""Week3-A105260034-魏嘉亨.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19fSGMi2H4cffQJslFYZc9BIL1hbbuyeD
"""

print("This is my homework ")

print("I'm ChiaHeng")

