# -*- coding: utf-8 -*-
"""Week8_A105260034_魏嘉亨_成果檢核.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gk6F4BMV_48_Np4ZLSLXnLSukviIYfmn
"""

#1存取串列中元素
s = input("請輸入一行英文句子?")
words = s.split(' ')
print("", words)
s2 = ' '.join(words)
print("", s2)
s3 = s.title()
print("",s3)

s = input('請輸入一行英文句子?')
s.strip(' .')
words = s.split(' ')
print(words[::-1])

#2找出及格的人
全班學生 = set(['John', 'Mary', 'Tina', 'Fiona', 'Claire', 'Eva', 'Ben', 'Bill', 'Bert'
])
英文及格 = set(['John', 'Mary', 'Fiona', 'Claire', 'Ben', 'Bill'])
數學及格 = set(['Mary', 'Fiona', 'Claire', 'Eva', 'Ben'])
print('英文與數學都及格', 英文及格&數學及格)
print('數學不及格', 全班學生-數學及格)
print('英文及格與數學不及格', 英文及格&(全班學生-數學及格))

#3找出兩首詩共同的字
p1 = '紅豆生南國,春來發幾枝?願君多采擷,此物最相思。'
p2 = '春眠不覺曉,處處聞啼鳥。夜來風雨聲,花落知多少。'
s1 = set(p1)
s1.remove(',')
s1.remove('。')
s1.remove('?')
s2 = set(p2)
s2.remove(',')
s2.remove('。')
print(s1&s2)

#4製作電子郵件通訊錄
mail = dict()
name = input('請輸入姓名?')
email = input('請輸入電子郵件?')
mail[name]=email
name = input('請輸入姓名?')
email = input('請輸入電子郵件?')
mail[name]=email
name = input('請輸入姓名?')
email = input('請輸入電子郵件?')
mail[name]=email
name = input('請輸入要查詢電子郵件的姓名?')
print(mail[name])

