# -*- coding: utf-8 -*-
"""Week4_A105260034_魏嘉亨.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12tKifu3f3N4_MRNjb-BKOA8NDzPb8Z3w
"""

print('學習',"Pythin",'真有趣')

name=input("請問貴姓大名?")
print("你好，",name)

print("學習Python真有趣")

name=input("請問貴姓大名?")
print("你好，",name)

a=1
print(a,id(a))
a="Python"
print(a,id(a))

b=True
print(b,type(b))
num=20
print(num,type(num))
pi=3.14
print(pi,type(pi))
s="Hello"
print(s,type(s))

print(bool(1))
print(bool(0))
print(bool(()))

print(int(100))
print(int(3.14))
print(int('100',2))

print(float(1))
print(float(3.14))
print(float('3.1415'))

s=str('Pythin')
s[0]='Q'

A=(5<2)
print(A)

A=(5<=2)
print(A)

A=(5>2)
print(A)

A=(5>=2)
print(A)

A=(5!=2)
print(A)

A=(5==2)
print(A)

x=1
y=[1,2,3]
print(x in y)

x=1
y=[1,2,3]
print(x not in y)

x=[1,2,3]
y=[1,2,3]
print(x is y)

x=[1,2,3]
y=[1,2,3]
print(x is not y)

x=[1,2,3]
y=[1,2,3]
print(id(x),id(y))
print(x is y)
print(x==y)

A=5+2
print(A)

A=5-2
print(A)

A=5*2

print(A)

A=5/2

print(A)

A=5//2

print(A)

A=5%2

print(A)

A=5**2

print(A)

a=(2+3*2)*(4-1)

print(a)

a=5
a=a+1

print(a)

a=5
a=a-1
print(a)

pow(2,10)

s='春眠不覺曉，處處聞啼鳥。\n\
夜來風雨聲，花落知多少。\n\
\t作者"孟浩然"詩名"春曉"'
print(s)

s1='春眠不覺曉，處處聞啼鳥，夜來風雨聲，花落知多少。'
list1=s1.split('，')
print(list1)

list1=['春眠不覺曉', '處處聞啼鳥', '夜來風雨聲', '花落知多少。']
s2='，'.join(list1)
print(s2)

s3=s1.replace('春','冬')
print(s3)

